export type SeatStatus = 'available' | 'selected' | 'booked' | 'premium';

export interface ISeat {
    //autogenerated
    id: string;
    showtime_id: string;
    row: string;
    number: number;
    //autogenerated
    seat_code: string;
    seat_status: SeatStatus;
}